#!/bin/sh

echo "Install Nmap, Nikto and SmbMap\n";
apt install -y docker.io pip git nmap nikto smbmap wapiti ldap-utils polenum smbclient wget ncrack arp-scan xsltproc wkhtmltopdf libmariadb-dev ;
pip install python-nmap python-libnmap pdfkit XlsxWriter json2html flask impacket xmltodict ldap3 PyYAML>=5.1;
pip3 install schedule mariadb whois;
